### ISSUE TITLE
Compression of files > 2GB broken

### ISSUE THREAD

**Issue by codeling** [Kitware/MetaIO#109]
A change (336c99d382bab223d1f3a6832b600a56acb92a65) in the cast that gets done to the `CompressedDataSize` field (see https://github.com/Kitware/MetaIO/blob/master/src/metaObject.cxx#L1490, probably done to address signedness mismatch) leads to problems loading files >2GB.
There can be a `bad_alloc` exception thrown when trying to decompress (raw) files larger 2GB (2^31) due to m_CompressedDataSize having a negative value.

**Comment by dzenanz** [comment]
Do you mind running the [update script](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/MetaIO/UpdateFromUpstream.sh) in ITK?

**Comment by codeling** [comment]
@dzenanz should I do that in master branch?

**Comment by dzenanz** [comment]
Yes, and make a PR to master too.

**Comment by codeling** [comment]
@dzenanz played around with that script a bit - and I can't figure out how it's supposed to be run.
when started with no parameters, with working directory either in its own folder, or the ITK root folder, it deletes a whole lot of files in the ITK repository itself....

**Comment by dzenanz** [comment]
Then I guess I will run it. Usually running from its own folder works. Perhaps we need to update that script for easier running, meaning less side-effects like deleting files outside of its folder.

**Comment by codeling** [comment]
> Then I guess I will run it.
thanks!

> Perhaps we need to update that script for easier running, meaning less side-effects like deleting files outside of its folder.
I was trying to run it from a git bash under windows, not from a Linux bash, maybe that makes some difference as well?

**Comment by dzenanz** [comment]
Sometimes it does, mostly it doesn't. I also use git bash on Windows usually.
