### ISSUE TITLE
Included zlib is version 1.2.3, which is from 2005 (!)

### ISSUE THREAD

**Issue by seanm** [Kitware/MetaIO#117]
1.2.3 was released in 2005 : http://madler.net/pipermail/zlib-announce_madler.net/2005/000004.html

Is some special procedure required to update it, or do we just change the files?

**Comment by dzenanz** [comment]
MetaIO is principally used by ITK and VTK, and both of those provide their own (much newer) ZLIB. I don't know the way to update it here, but it is a low-value effort.

**Comment by seanm** [comment]
Perhaps just removing it then?

**Comment by dzenanz** [comment]
That might break this repo's tests.

**Comment by seanm** [comment]
Well, I bothered to report this because:

1. this version of zlib does not compile as [C23](https://en.wikipedia.org/wiki/C23_(C_standard_revision))
2. there are known security vulnerabilities in this old zlib

**Comment by dzenanz** [comment]
Feel free to try updating it. Make a PR if successful, explain here what went wrong if not 😄

**Comment by seanm** [comment]
I may give it a shot, but since I don't even use MetaIO, it's not high on my list...

I see VTK has `VTK_MODULE_ENABLE_VTK_metaio` that I can set to `NO`, but I don't find anything similar for ITK, is there?

**Comment by aylward** [comment]
Why do you want to disable it?  It should be using the zlibs from ITK and VTK and not compiling its own.  Or are you disabling all zlib compilation/usage?

**Comment by dzenanz** [comment]
You need to set `ITK_BUILD_DEFAULT_MODULES`, `BUILD_TESTING`, `ITKGroup_IO`, and even `ITKGroup_Core` to OFF for the following option to appear: `Module_ITKIOMeta`. MetaImage is a lot more important to ITK than to VTK.

**Comment by seanm** [comment]
>Why do you want to disable it?

Risk mitigation.  I don't use it, and disabling it reduces the risk of accidentally using the ancient zlib.

**Comment by seanm** [comment]
>You need to set ITK_BUILD_DEFAULT_MODULES, BUILD_TESTING, ITKGroup_IO, and even ITKGroup_Core to OFF for the following option to appear: Module_ITKIOMeta. MetaImage is a lot more important to ITK than to VTK.

Ah, which I believe is almost the same as 'you can't disable it'. :)

**Comment by seanm** [comment]
Fixed by: https://github.com/Kitware/MetaIO/pull/120
