### ISSUE TITLE
Documentation & magic bytes

### ISSUE THREAD

**Issue by timholy** [Kitware/MetaIO#38]
The documentation seems somewhat sparing (see my comments [here](https://github.com/JuliaIO/MetaImageFormat.jl)). One thing I most want to know is whether the `ObjectType` field is guaranteed to come first: if so, then I can use it for magic bytes in [Julia's general "figure out what type of file this is"](https://github.com/JuliaIO/FileIO.jl) library.

**Comment by thewtex** [comment]
The reference documentation is here:

  https://itk.org/Wiki/MetaIO/Documentation

and the reference implementation is this repository.

I do not see an explicit guarantee that `ObjectType` will come first, but it is a reasonable assumption.

**Comment by timholy** [comment]
If you plan to change the format in the future, may I suggest that inserting a version number and guaranteed magic bytes into the header would be a nice improvement?

**Comment by thewtex** [comment]
@timholy Yes, good idea.
