### ISSUE TITLE
MET_TypeToString() -Wtautological-unsigned-zero-compare discussion...

### ISSUE THREAD

**Issue by seanm** [Kitware/MetaIO#39]
clang trunk in r312750 learned to warn about tautological comparison of an unsigned value with signed zero:

http://llvmweekly.org/issue/193

https://reviews.llvm.org/rL312750

and now on one of my VTK dashboards there is 1 and only 1 such warning:

```
/Users/builder/external/VTK/Utilities/MetaIO/vtkmetaio/metaUtils.cxx:241:12: warning: comparison of unsigned enum expression >= 0 is always true [-Wtautological-unsigned-zero-compare]
  if(_vType>=0 && _vType<=MET_NUM_VALUE_TYPES)
     ~~~~~~^ ~
1 warning generated.
```

Instead of a pull request, I thought I'd open an issue, because I'm not sure how you'd like to fix this.  The entire check shouldn't be necessary because an enum can't hold a value outside its range.  Shall we just remove it?  Also, maybe I need more coffee, but shouldn't that <= be < ?

**Comment by jcfr** [comment]
Thanks for the report.

> Shall we just remove it?

By principle, an enum could be int or unsigned int (see http://en.cppreference.com/w/cpp/language/enum), may be we should simply silence the warning ?


> Also, maybe I need more coffee, but shouldn't that <= be < ?

Indeed, since it represents the number of values .. I also think it should be `<`

**Comment by seanm** [comment]
It can be int or unsigned int, but this enum can indeed never be < 0 because its first value is 0 and its last value is 28.  In the article you linked to: "...the range is all values possible for the smallest bit field large enough to hold all enumerators of the target enumeration."  So this enum can't hold anything outside 0 to 31, inclusive.  So the _vType<MET_NUM_VALUE_TYPES should in fact be kept.  But it should be safe to remove >= 0, as per the warning.

**Comment by jcfr** [comment]
Good point. Sounds good then. :+1:

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/Kitware/MetaIO/commit/998bd201009c732769aaa265847ad2ad92a507c0
