### ISSUE TITLE
Require C++11 now that ITK and VTK require it

### ISSUE THREAD

**Issue by seanm** [Kitware/MetaIO#59]
Now that VTK & ITK do, can MetaIO require C++11 at this point?

Especially small things like use of 'override' and 'nullptr'.

Those 2 could be done automatically with clang-tidy (I volunteer).

It would allow me to enable additional warnings on my VTK dashboards...

**Comment by dzenanz** [comment]
I suppose that would be welcome.

**Comment by seanm** [comment]
Is that a definitive statement? :)  I don't want to waste my time after all... :)

**Comment by dzenanz** [comment]
I think that @thewtex and @jcfr can give the definitive statement. Wait for their comment.

**Comment by jcfr** [comment]
Sounds good to me. @matt: may be we could tag a release before proceeding ?
Release tag could be of the form YYYY-DD-MM

**Comment by seanm** [comment]
https://github.com/Kitware/MetaIO/pull/61

**Comment by thewtex** [comment]
> Sounds good to me. @matt: may be we could tag a release before proceeding ? Release tag could be of the form YYYY-DD-MM

We could tag, but I don't know if it would add any benefit.

**Comment by dzenanz** [comment]
Closed by #62.
