### ISSUE TITLE
Installation path of header files

### ISSUE THREAD

**Issue by schuhschuh** [Kitware/MetaIO#86]
When building and installing this MetaIO library stand-alone, with `CMAKE_INSTALL_PREFIX=/opt/metaio` on macOS, the installed files are:

```
/opt/metaio
├── include
│   ├── itkMetaIO
│   │   ├── itkThirdParty.h
│   │   ├── itk_zlib.h
│   │   └── metaIOConfig.h
│   ├── localMetaConfiguration.h
│   ├── metaArray.h
│   ├── metaArrow.h
│   ├── metaBlob.h
│   ├── metaCommand.h
│   ├── metaContour.h
│   ├── metaDTITube.h
│   ├── metaEllipse.h
│   ├── metaEvent.h
│   ├── metaFEMObject.h
│   ├── metaForm.h
│   ├── metaGaussian.h
│   ├── metaGroup.h
│   ├── metaIOConfig.h
│   ├── metaITKUtils.h
│   ├── metaImage.h
│   ├── metaImageTypes.h
│   ├── metaImageUtils.h
│   ├── metaLandmark.h
│   ├── metaLine.h
│   ├── metaMesh.h
│   ├── metaObject.h
│   ├── metaOutput.h
│   ├── metaScene.h
│   ├── metaSurface.h
│   ├── metaTransform.h
│   ├── metaTube.h
│   ├── metaTubeGraph.h
│   ├── metaTypes.h
│   ├── metaUtils.h
│   └── metaVesselTube.h
└── lib
    └── libITKMetaIO.a
```

The `localMetaConfiguration.h` contains the statement `#include "itk_zlib.h"`, but this header file is in subdirectory `itkMetaIO`, requiring the addition of this include path to the list of include search paths. It seems to me that the install paths of the header files are inconsistent.

For comparison, when build and installed as part of ITK with `CMAKE_INSTALL_PREFIX=/opt/itk`, all header files of MetaIO end up in `/opt/itk/include/ITK-$major.$minor/`. Given this, I would expect that all header files of the stand-alone MetaIO library would end up in `/opt/metaio/include/itkMetaIO` instead of the top-level include directory.

Alternatively, the `itkMetaIO` subdirectory could be dropped from the stand-alone installation, given the `itk` file name prefixes and redundant `itkMetaIO/metaIOConfig.h`?

**Comment by dzenanz** [comment]
I am not sure that anyone uses MetaIO directly. Even [Slicer](https://github.com/Slicer/Slicer) just has two copies for MetaIO, one through ITK the other one through VTK. This is possible as both ITK and VTK have their own name mangling scheme for it. You are welcome to fix standalone use case, as long as you don't break ITK's and VTK's usage of MetaIO.

**Comment by schuhschuh** [comment]
Yeah, I thought so.

I am also in the process of integrating it via copy into my software (MIRTK) directly rather after looking at ITK and VTK. Just noticed this discrepancy in installation directories and thought I'd bring it up. It may also be good if users of my library could install the latest stand-alone MetaIO from this repository instead, which I could then pick up with a custom `FindMetaIO` module to link compile and link against.
